web/router.ex
# Copyright 2016 Ingage Partners
#
# This file is part of Contributr.
#
# Contributr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Contributr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Contributr.  If not, see <http://www.gnu.org/licenses/>.
defmodule Contributr.Router do
  use Contributr.Web, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin do
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :organization do
  end

  #TODO: make a plug that only allows superadmins in here
  scope "/admin", Contributr do
    pipe_through [:browser, :admin] # Use the default browser stack
    resources "/users", UserController
    resources "/orgs", OrgController
    resources "/roles", RoleController
    resources "/:organization/events", EventController
    resources "/:organization/users", EventUsersController
    get "/:organization/event_users/:event_id", EventUsersController, :list
    get "/:organization/event_users/:event_id/:id/comments", EventUsersController, :list_comments
    get "/:organization/event_users/:event_id/new", EventUsersController, :new_event_user
    get "/:organization/event_users/:event_id/:id/edit", EventUsersController, :edit_event_user
    get "/:organization/event_users/:event_id/:id/delete", EventUsersController, :delete_event_user
    put "/:organization/event_users/:event_id/:id/update", EventUsersController, :update
    patch "/:organization/event_users/:event_id/:id/update", EventUsersController, :update
    post "/:organization/event_users/:event_id", EventUsersController, :create_event_user

  end

  scope "/auth", Contributr do
    pipe_through [:browser]
    get "/logout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", Contributr do
    pipe_through [:browser]

    # the home page
    get "/", PageController, :index
    get "/login", LoginController, :index
  end

  scope "/:organization", Contributr do

    pipe_through [:browser, :organization]

    get "/", ApplicationController, :index

    resources "/user", UserController
    get "/user/bulk/add", UserController, :bulk_add
    post "/user/bulk/create", UserController, :bulk_create
    resources "/orgusers/:event_id", OrgUserController
    resources "/contributions/:event_id", ContributionController
    resources "/comments/:event_id", OrgUserCommentController
  end

end

web/templates/page/index.html.eex
<div>
    <span>
        <div class="mui--align-bottom mui--text-center mui--text-dark-secondary mui-row mui--clearfix">
            <div class="mui--align-bottom mui--text-left mui--text-display1 mui-row mui-col-md-8">Events</div>
            <div class="mui-panel mui--appbar-line-height mui--invisible mui-col-md-8"></div>
            <% events = @current_user.events %>
             <%= for event <- events do %>

                    <div class="mui-panel mui--clearfix mui--bg-primary-dark mui-col-md-8">
                        <div class="mui-panel mui--clearfix">
                            <span class="mui--align-bottom mui--pull-left mui--text-title"><b><%= event.name %></b></span>
                            <span class="mui--align-bottom mui--pull-right mui--text-headline"><ul class="mui-list--inline"><li>End Date</li><li><%= event.end_date%></li></ul>
                        </div>
                        <span class="mui--appbar-min-height">
                       <%= if  @current_user.role_name == "Superadmin" do %>
                           <!-- begin event admin section -->
                           <ul class="mui-list--inline mui--text-left">
                           <li><a href='<%= event_path(@conn, :edit, @current_user.org_name, event.id) %>' class='mui-btn mui-btn--small mui-btn--raised mui-btn--danger'>
                              Edit
                           </a></li>
                           <li><a href='<%=  event_users_path(@conn, :list, @current_user.org_name, event.id) %>' class='mui-btn mui-btn--small mui-btn--raised mui-btn--danger'>
                              Participants
                           </a></li>
                           </ul>
                           <!-- end event admin section -->
                       <% else %>
                           <!-- user options -->
                           <a href='<%= contribution_path(@conn, :index,@current_user.org_name, event.id) %>' class='mui-btn mui-btn--small mui-btn--raised mui-btn--accent'>
                              Start !
                           </a>
                       <% end %>
                       </span>
                    </div>
             <% end %>
             <!-- begin application admin section -->
             <%= if(@current_user.role_name == "Superadmin") do %>
             <div class="mui--align-bottom mui--text-left mui--text-display1 mui-col-md-8">Manage</div>
             <div class="mui-panel mui--appbar-line-height mui--invisible"></div>
             <div class="mui--appbar-min-height mui-panel mui--clearfix mui--bg-primary-dark ">
                   <ul class="mui--text-left mui--appbar-min-height mui-list--inline">
                     <li><a href='<%=event_path(@conn, :new, @current_user.org_name )%>' class='mui-btn mui-btn--small mui-btn--raised mui-btn--danger'>Add new event</a></li>
                     <li><a href='<%=user_path(@conn, :bulk_add,@current_user.org_name )%>' class='mui-btn mui-btn--small mui-btn--raised mui-btn--danger'>Add new user to org</a></li>
                   </ul>
            </div>
            <% end %>
             <!-- end application admin section -->
        </div>
    </span>
</div>